version: '2'
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    image: itsgoingtobe/app
    volumes:
      - ./app/src:/app/src
    ports:
      - "3000:3000"

  # storybook:
  #   build:
  #     context: ./app
  #     dockerfile: ../docker/storybook/Dockerfile
  #   image: itsgoingtobe/storybook
  #   volumes:
  #     - ./app/src:/app/src
  #     - ./app/stories:/app/stories
  #   ports:
  #     - "6006:6006"

  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile
    image: itsgoingtobe/server
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/itsgoingtobe

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=itsgoingtobe
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  # mysql_test:
  #   image: mysql:8.0
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=itsgoingtobe
  #     - MYSQL_USER=user
  #     - MYSQL_PASSWORD=password