version: '3.8'
services:
  app:
    image: itsgoingtobe/app:latest
    command: npm run start
    volumes:
      - ./app:/app
      - /app/node_modules
    expose:
      - "3000"
    environment:
      - PORT=3000

  storybook:
    image: itsgoingtobe/app:latest
    command: npm run storybook
    volumes:
      - ./app:/app
      - ./app/node_modules
    ports:
      - "6006:6006"

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./server/swagger.yml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml
    ports:
      - "4000:8080"

  server:
    image: itsgoingtobe/server:latest
    command: npm run start
    depends_on:
      - mysql
    volumes:
      - ./server:/server
      - /server/node_modules
    expose:
      - "8001"
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/itsgoingtobe
      - PORT=8001
      - JWT_PASSPHRASE=secret
      - NODE_ENV=development

  webserver:
    image: nginx:alpine
    depends_on:
      - app
      - server
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  mysql:
    image: mysql:8.0
    expose:
      - "3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=itsgoingtobe
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
