version: '2'
services:
  app:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    image: itsgoingtobe/app
    volumes:
      - ./app/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  # storybook:
  #   build:
  #     context: ./app
  #     dockerfile: ../docker/storybook/Dockerfile
  #   image: itsgoingtobe/storybook
  #   volumes:
  #     - ./app/src:/app/src
  #     - ./app/stories:/app/stories
  #   ports:
  #     - "6006:6006"

  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile
    image: itsgoingtobe/server
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./server:/server
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/itsgoingtobe
      - PORT=8001
      - JWT_TOKEN_SECRET=secret

  webserver:
    image: nginx:alpine
    depends_on:
      - app
      - server
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=itsgoingtobe
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
